# -*- coding: utf-8 -*-
"""IRIS FLOWER CLASSIFICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJWp4GfnEz7QKljAFizB53FGFBke9Apy
"""

# TASK 3 - IRIS FLOWER CLASSIFICATION
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import warnings
warnings.filterwarnings('ignore')

# 1. LOAD DATA
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

print("Shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())
print("\nClass distribution:")
print(df['species'].value_counts())

# 2. VISUALIZATIONS
# Pairplot
sns.pairplot(df, hue='species', palette='Set2')
plt.suptitle('Iris Pairplot', y=1.02)
plt.savefig('iris_pairplot.png', bbox_inches='tight')
plt.show()

# Correlation heatmap
plt.figure(figsize=(8,5))
sns.heatmap(df.drop('species', axis=1).corr(), annot=True, cmap='coolwarm')
plt.title('Feature Correlation Heatmap')
plt.savefig('iris_heatmap.png', bbox_inches='tight')
plt.show()

# 3. PREPARE DATA
X = df.drop('species', axis=1)
y = iris.target   # 0, 1, 2

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# 4. TRAIN 5 MODELS
models = {
    'Logistic Regression': LogisticRegression(max_iter=200),
    'Decision Tree':       DecisionTreeClassifier(random_state=42),
    'Random Forest':       RandomForestClassifier(n_estimators=100, random_state=42),
    'SVM':                 SVC(kernel='rbf', random_state=42),
    'KNN':                 KNeighborsClassifier(n_neighbors=5)
}

results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    cv  = cross_val_score(model, X, y, cv=5).mean()
    results[name] = {'Test Accuracy': acc, 'CV Accuracy': cv}
    print(f"\n{'='*40}")
    print(f"Model: {name}")
    print(f"Test Accuracy: {acc:.4f} | CV Accuracy: {cv:.4f}")
    print(classification_report(y_test, y_pred,
                                 target_names=iris.target_names))

# ── 5. ACCURACY BAR CHART ─────────────────────────────────────
names = list(results.keys())
test_accs = [results[n]['Test Accuracy'] for n in names]
cv_accs   = [results[n]['CV Accuracy']   for n in names]

x = np.arange(len(names))
width = 0.35
fig, ax = plt.subplots(figsize=(10,5))
ax.bar(x - width/2, test_accs, width, label='Test Accuracy', color='steelblue')
ax.bar(x + width/2, cv_accs,   width, label='CV Accuracy',   color='coral')
ax.set_xticks(x); ax.set_xticklabels(names, rotation=15)
ax.set_ylim(0.8, 1.02); ax.set_ylabel('Accuracy')
ax.set_title('Model Comparison – Iris Classification')
ax.legend()
plt.tight_layout()
plt.savefig('iris_model_comparison.png')
plt.show()

# ── 6. CONFUSION MATRIX for best model (Random Forest) ────────
rf = models['Random Forest']
cm = confusion_matrix(y_test, rf.predict(X_test))
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=iris.target_names,
            yticklabels=iris.target_names)
plt.title('Random Forest – Confusion Matrix')
plt.ylabel('Actual'); plt.xlabel('Predicted')
plt.savefig('iris_confusion_matrix.png')
plt.show()

# ── 7. PREDICT ON CUSTOM FLOWER ───────────────────────────────
custom = np.array([[5.1, 3.5, 1.4, 0.2]])   # change these values to test
pred = rf.predict(custom)
print(f"\nCustom prediction for {custom}: {iris.target_names[pred[0]]}")