# -*- coding: utf-8 -*-
"""salespridictionusingpython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Llaud-y_Z1BOU7jOnCUsB5cjuJGaRsxA
"""

# ── COMPLETE SALES PREDICTION SCRIPT ──────────────────────────────────

# STEP 1: ALL IMPORTS (run this first, everything depends on it)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import warnings
warnings.filterwarnings('ignore')

# STEP 2: LOAD DATA
df = pd.read_csv('advertising.csv')
print("Shape:", df.shape)
print(df.head())
print("\nMissing Values:\n", df.isnull().sum())

# STEP 3: EDA
plt.figure(figsize=(7, 5))
sns.heatmap(df.corr(), annot=True, fmt='.2f', cmap='coolwarm')
plt.title('Correlation Matrix')
plt.tight_layout()
plt.savefig('sales_corr.png', dpi=150)
plt.show()

feature_cols = [c for c in df.columns if c.lower() != 'sales']
target_col   = [c for c in df.columns if c.lower() == 'sales'][0]

fig, axes = plt.subplots(1, len(feature_cols), figsize=(5 * len(feature_cols), 4))
colors = ['steelblue', 'coral', 'seagreen']

for ax, feat, color in zip(axes, feature_cols, colors):
    ax.scatter(df[feat], df[target_col], alpha=0.5, color=color, s=20)
    ax.set_xlabel(feat)
    ax.set_ylabel(target_col)
    ax.set_title(f'{feat} vs {target_col}')

plt.tight_layout()
plt.savefig('sales_scatter.png', dpi=150)
plt.show()

# STEP 4: PREPROCESSING
df.dropna(inplace=True)

X = df[feature_cols]
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print(f"\nTrain: {X_train.shape}, Test: {X_test.shape}")

# STEP 5: TRAIN MODELS
models = {
    'Linear Regression':  LinearRegression(),
    'Ridge Regression':   Ridge(alpha=1.0),
    'Lasso Regression':   Lasso(alpha=0.1),
    'Random Forest':      RandomForestRegressor(n_estimators=100, random_state=42),
    'Gradient Boosting':  GradientBoostingRegressor(n_estimators=100, random_state=42)
}

results = {}

for name, model in models.items():
    if 'Regression' in name:
        model.fit(X_train_sc, y_train)
        preds = model.predict(X_test_sc)
    else:
        model.fit(X_train, y_train)
        preds = model.predict(X_test)

    mae  = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    r2   = r2_score(y_test, preds)

    results[name] = {'MAE': mae, 'RMSE': rmse, 'R2': r2, 'preds': preds}

    print(f"\n{'='*40}")
    print(f"Model : {name}")
    print(f"  MAE : {mae:.4f}")
    print(f"  RMSE: {rmse:.4f}")
    print(f"  R²  : {r2:.4f}")

# STEP 6: ACTUAL vs PREDICTED PLOT
fig, axes = plt.subplots(1, len(models), figsize=(5 * len(models), 4))

for ax, (name, res) in zip(axes, results.items()):
    ax.scatter(y_test, res['preds'], alpha=0.6, s=20, color='steelblue')
    lims = [min(y_test.min(), res['preds'].min()),
            max(y_test.max(), res['preds'].max())]
    ax.plot(lims, lims, 'r--', lw=1.5)
    ax.set_title(f"{name}\nR²={res['R2']:.3f}")
    ax.set_xlabel('Actual')
    ax.set_ylabel('Predicted')

plt.tight_layout()
plt.savefig('sales_predictions.png', dpi=150)
plt.show()

# STEP 7: R² COMPARISON CHART
metrics_df = pd.DataFrame({
    'R²'  : {k: v['R2']   for k, v in results.items()},
    'RMSE': {k: v['RMSE'] for k, v in results.items()},
    'MAE' : {k: v['MAE']  for k, v in results.items()}
})

metrics_df[['R²']].plot(kind='bar', figsize=(9, 4),
                         color='steelblue', edgecolor='white', legend=False)
plt.title('R² Score Comparison')
plt.ylabel('R²')
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.savefig('sales_r2.png', dpi=150)
plt.show()

# STEP 8: FEATURE IMPORTANCE
rf = models['Random Forest']
feat_imp = pd.Series(rf.feature_importances_, index=feature_cols).sort_values(ascending=False)

plt.figure(figsize=(7, 4))
feat_imp.plot(kind='bar', color='coral')
plt.title('Feature Importances – Random Forest')
plt.tight_layout()
plt.savefig('sales_features.png', dpi=150)
plt.show()

# STEP 9: BEST MODEL + NEW PREDICTION
best = max(results, key=lambda k: results[k]['R2'])
print(f"\nBest model: {best} → R²={results[best]['R2']:.4f}, RMSE={results[best]['RMSE']:.4f}")

sample = pd.DataFrame([[200, 40, 10]], columns=feature_cols)
rf_pred = models['Random Forest'].predict(sample)
print(f"\nPredicted Sales for TV=200, Radio=40, Newspaper=10 → {rf_pred[0]:.2f}")